memo_app
shu913/memo_app pull request #1
Opened 2022-07-23 10:25 UTC by shu913

2022-07-28 06:42 UTC, func09 requested changes
レビューしました！
主にURL周りについてコメントしています。
RESTのプラクティスを思い出して、再提出お願いします！

2022-07-28 06:42 UTC, func09 commented on memo_app.rb
> +patch '/memos/:id/edit' do
惜しい！更新（PATCH）のURLには `edit` は不要です。

2022-07-28 06:42 UTC, func09 commented on memo_app.rb
> +get '/edit/:id' do
ここも惜しい。

`/memos/:id` というリソースを編集する画面と考えたら、URLはどうなりますか？

2022-07-28 06:42 UTC, func09 commented on memo_app.rb
> +get '/' do
👍

2022-07-28 06:42 UTC, func09 commented on memo_app.rb
> +get '/new' do
ここも RESTにならったURLをおさらいして考えましょう。

あたらしいメモ（`/memos`）の新しいリソースを作成する画面（`new`）と考えたらURLはどうなりますか？

2022-07-29 04:30 UTC, shu913 commented on memo_app.rb
> +get '/new' do
`/memos/new`という形で修正しました。

2022-07-29 04:30 UTC, shu913 commented on memo_app.rb
> +get '/edit/:id' do
`/memos/:id/edit`という形で修正しました。

2022-07-29 04:31 UTC, shu913 commented on memo_app.rb
> +patch '/memos/:id/edit' do
editの部分を削除しました。

2022-07-29 11:51 UTC, func09 approved these changes
LGTM~ばっちりです！

2022-07-29 11:51 UTC, func09 commented on memo_app.rb
> +get '/memos/new' do
👍

2022-07-30 05:49 UTC, merged